const { View,Text,Image,ImageBackground, ScrollView} = require("react-native");
const logo = require("./assets/adaptive-icon.png");
export default function App() {
    return (
        <View style={{ flex: 1, backgroundColor: "plum", padding: 60 }}>
            <ScrollView>
                <Text>
                    hello
                    <Text style={{ color: "yellow" }}>world!</Text> how r u ?{" "}
                </Text>
                <Image source={logo} style={{ width: 300, height: 300 }} />
                <ImageBackground
                    style={{ flex: 1, width: 300, height: 300 }}
                    source={{ uri: "https://picsum.photos/300" }}
                >
                    <Text>hello</Text>
                </ImageBackground>
                <Text>
                   Lorem ipsum dolor sit amet consectetur adipisicing elit. Est assumenda vel sint explicabo officia perferendis alias voluptates blanditiis, ea rerum. Nihil dignissimos in blanditiis quaerat alias illum assumenda beatae similique!
                   Ipsum ex autem maiores explicabo id distinctio. Sed quae fugiat accusamus architecto ex ut nisi et illo, dolore laborum reprehenderit blanditiis nam provident saepe ipsam eveniet corrupti quibusdam voluptas voluptatem.
                   Tenetur facilis alias omnis quidem aut dicta dignissimos quo deserunt quibusdam neque blanditiis, maiores, quas hic dolorum cumque. Dolorem, maxime distinctio et maiores necessitatibus dolor harum laudantium dolore aperiam suscipit.
                   Consectetur sit officia nobis delectus itaque non dicta quod eveniet magnam? Optio voluptatem fuga ea similique. Ducimus, sit. Harum tempore modi soluta nobis blanditiis culpa unde doloremque necessitatibus incidunt labore?
                   In, commodi ex totam numquam asperiores facere reiciendis at fugiat sed consequuntur quisquam maxime dolor deleniti dolorum nemo illo quia provident fugit doloremque. Eos aut tempora facilis sed asperiores ab.
                   Fugiat blanditiis aliquid corporis voluptatem libero, dolores quibusdam deserunt sed magnam nam eaque cum ex nostrum est facere perferendis incidunt voluptates accusamus minus odio beatae dolorem veritatis? Dolorum, ut amet.
                   Impedit, fugit cum amet natus, necessitatibus voluptas quae recusandae perspiciatis labore exercitationem quod aliquam tempora sunt vel consequatur magni enim itaque laboriosam est quibusdam. Suscipit voluptas mollitia illum et consequatur.
                   Tempora unde delectus obcaecati ipsa nobis nihil sed sapiente quod similique quam qui ad labore veritatis culpa blanditiis aut, fugiat adipisci accusantium magni dicta. Quis, excepturi explicabo? Consequuntur, culpa quam?
                   Quasi amet aspernatur consequuntur facilis possimus similique! Iure aperiam autem repellendus quibusdam. Sunt, recusandae nemo deserunt porro nam doloremque cumque laudantium quia enim explicabo quasi soluta a quae ullam dolores.
                   Itaque voluptatem consectetur ad? Quas sequi accusamus sit quo quam cumque amet nostrum voluptates maxime consectetur asperiores voluptatem quae nulla quos minus repudiandae fugit numquam aliquid, qui harum veritatis! Aut!
                   Iusto cum voluptate eligendi deserunt minima obcaecati, suscipit nihil at sint. Cum corrupti quidem cumque molestias, doloremque eligendi explicabo suscipit! Quas in sunt maxime? Omnis placeat beatae quisquam iste ullam?
                   Nesciunt et repellendus eaque adipisci, quam minima, illum accusamus nam in laborum itaque neque! Adipisci ab cumque quod odit modi, sint distinctio officia alias ipsa numquam ut fuga rerum earum.
                   Doloremque porro quis accusamus officiis ipsum, blanditiis sequi ratione vero. Ex, possimus eius qui eum quia tenetur soluta. Rerum ab delectus totam obcaecati natus maxime placeat maiores ipsa aperiam iusto!
                   Laborum quae vero dignissimos corrupti sint asperiores assumenda nulla distinctio, magnam repudiandae molestiae voluptate rem quibusdam quia consectetur necessitatibus a architecto cupiditate reprehenderit mollitia. Ex nihil quibusdam ullam aliquid repellendus!
                   Corrupti repellendus quisquam, aperiam ex quis iste labore molestias! Optio cumque fugit illo, adipisci cum voluptate! Non unde eveniet minus saepe. Doloremque veniam perferendis repudiandae illo commodi similique voluptatem quidem?
                   Quod a voluptatum, qui, autem id explicabo aliquid quis molestiae ratione perspiciatis itaque. Voluptas ipsam optio porro sequi asperiores harum cum, doloremque adipisci? Quisquam molestias asperiores facere sed nulla et!
                   Modi, quas optio. Minima quisquam dolorum dicta hic ab, reiciendis eveniet ipsam ipsum expedita tempora omnis fuga doloremque magni laboriosam suscipit ex, eos nesciunt aut. Reprehenderit soluta at cupiditate et.
                   Reiciendis voluptatum dolorum placeat aspernatur, iusto cum, quisquam architecto error ipsum, ad molestias unde accusantium magnam. Dolorum accusamus cum nulla necessitatibus dignissimos maxime officia consectetur culpa porro, quas molestiae sequi.
                   Laboriosam incidunt obcaecati amet facere maxime, praesentium eligendi. Rerum maiores dolore ea similique nisi error illo provident sit reprehenderit nobis aspernatur, quisquam odit ipsum neque numquam ad soluta inventore magni.
                   Veniam hic eaque nihil aperiam odio. Omnis aliquam ab totam enim qui nostrum tempora error asperiores fugit corrupti voluptate eveniet quidem corporis, cupiditate exercitationem in dolorem accusantium quo architecto similique?
                   Nostrum quia mollitia sequi, molestiae, ad, error vel consectetur inventore odio nisi veritatis eos soluta distinctio? Officia voluptatem unde fugit, hic tempora harum maxime, obcaecati maiores nam expedita veniam. Libero.
                   Ab sequi voluptates sapiente perferendis, repellat optio itaque beatae praesentium libero magnam quis quibusdam perspiciatis vel, blanditiis id exercitationem dolores pariatur officiis dignissimos dolorem cupiditate, ratione fuga. Dolor, ducimus labore?
                   Qui delectus iusto aspernatur voluptate repellat quidem expedita, quas ad voluptatem rerum explicabo quos nemo amet officia? Temporibus nobis, ullam rerum dolore necessitatibus praesentium odio! Rerum, non. Odit, dignissimos porro.
                   Nihil, consequatur obcaecati quam dolor, assumenda, natus similique odio asperiores in voluptates quibusdam. Facere deserunt voluptatibus, praesentium obcaecati dignissimos cumque laboriosam ipsum unde voluptatem, asperiores, incidunt rerum repudiandae impedit! Aperiam?
                   Tempore soluta sapiente error asperiores optio facilis enim illum ut velit sunt, hic odio cum, deleniti accusantium dolorum aliquam suscipit, eligendi ab fugit consequuntur maxime. Itaque deserunt consequatur nemo quasi.
                   Nisi, tempore soluta. Pariatur sint nam possimus. Repellendus et, nulla corporis dolor error totam ipsa tempore est, blanditiis, suscipit animi temporibus. Aut consequatur iste debitis eaque perferendis voluptas sed omnis.
                   Ut natus velit, deserunt, eligendi nobis consectetur quo quia alias tempora debitis quam ducimus. Impedit incidunt error animi cupiditate vel, consequatur unde dolores. Placeat a aperiam accusantium. Ipsa, corporis vero.
                   Pariatur, rerum. Recusandae nostrum cum corrupti, laborum eveniet temporibus voluptate ipsum voluptas eius. Optio eligendi ad nam minus dolorem obcaecati consectetur, sit corporis illo libero nesciunt dolor asperiores id unde!
                   Recusandae quae fuga explicabo optio, quidem id aliquid ut ratione dignissimos dolorem enim asperiores. At vero, facere, quasi expedita fugiat unde obcaecati quis culpa recusandae repellat quidem, molestias dolores assumenda!
                   Reiciendis adipisci delectus facilis consequuntur autem beatae ducimus. Consectetur atque, ipsum voluptate vero blanditiis beatae aperiam, porro rem quia perspiciatis repellat fugit quod mollitia soluta molestias sed magnam! Esse, blanditiis?
                   Rerum sed non, ea unde molestias earum animi ullam, eos culpa consequuntur maiores facere rem dolore, quod et quia quasi repellat reiciendis? Explicabo, exercitationem? Maiores autem voluptate dolor tempora excepturi.
                   Repellendus harum blanditiis aliquam ad doloribus officiis nemo quam in, aspernatur adipisci deleniti laboriosam! Voluptatum dolor nostrum ipsa in, optio aliquid, non repellat fuga iste nobis eum modi repellendus rerum.
                   At distinctio, delectus illo ad laudantium facere animi repellendus nihil saepe necessitatibus molestias id deserunt quasi hic impedit alias, ut, explicabo iste in deleniti iusto optio sed maiores! Voluptates, nobis?
                   A temporibus harum ut recusandae consequatur. Architecto facilis commodi, molestiae quis temporibus ipsam recusandae eum quia hic veritatis porro magni sunt eaque quasi voluptas ratione aliquam rerum dolorem repellat adipisci.
                   Nam pariatur laborum eum provident consectetur alias doloremque incidunt nesciunt excepturi quasi vel, dolor, veniam officiis similique odio at sint inventore, ducimus eaque deserunt aut. Et accusamus architecto assumenda incidunt?
                   Veniam consequuntur eum, exercitationem ipsa pariatur provident vitae recusandae ullam esse error, adipisci illo deserunt accusamus inventore, non eius molestiae voluptatem! Similique sit corrupti saepe eius commodi. Voluptatem, odio ut!
                   Magni beatae nemo recusandae asperiores. Eum magnam earum commodi alias esse tempore amet praesentium ratione, numquam ab soluta. Doloribus sit debitis cupiditate maxime iusto similique ex voluptates a quasi nam.
                   Impedit aliquid assumenda qui a? Autem voluptatum illum id expedita doloribus consequuntur officiis natus totam omnis, cum asperiores ad non cupiditate, sint, ducimus provident magnam accusantium quaerat molestias labore atque!
                   Asperiores officia id dolorem, distinctio quae, rerum tenetur quos, quisquam est ex adipisci accusantium explicabo laborum corrupti illo. Officiis earum quam accusantium illo, qui eligendi. Maxime illum delectus quod dolor?
                   Assumenda provident quidem neque, architecto eveniet ipsa, numquam ex qui culpa quas, consequatur ratione dicta commodi molestiae sint minus laborum ullam perferendis rem. Architecto illo similique iste nulla fuga maiores?
                   Nulla, repudiandae ratione suscipit eveniet corporis maxime, deserunt perspiciatis aperiam ex voluptatum labore quasi quaerat. Eaque voluptatibus nihil, voluptates quos quibusdam ea incidunt quod asperiores aspernatur, labore ex eveniet minus.
                   Aspernatur qui aliquid architecto ipsam et, ab commodi placeat veritatis totam, ipsum minus aliquam laborum molestias suscipit quaerat itaque accusamus voluptate debitis voluptatem dolor. Voluptas nulla unde adipisci ea beatae.
                   Excepturi, possimus, adipisci dicta aspernatur deleniti accusantium in ullam corrupti expedita ducimus necessitatibus ut similique asperiores architecto! Assumenda incidunt unde repudiandae. Neque quaerat iusto tenetur dolorem error? Doloribus, hic cumque!
                   Fugit numquam ea commodi. Laborum asperiores fugit labore cum, earum distinctio, suscipit architecto eligendi laudantium excepturi quidem perferendis id eveniet mollitia iste tempore unde sequi quam, eos est nisi magni!
                   Voluptate rem optio qui saepe. Quos quae modi officiis error, corporis id nulla incidunt velit maiores, praesentium cupiditate rerum porro veritatis aut earum iure. Tenetur minus veniam nostrum iure culpa!
                   Voluptatem quis tempore consectetur? Alias excepturi recusandae ipsam magnam. Quo nam laboriosam voluptas ipsam, aspernatur maiores temporibus, rerum odio officiis ad facere qui consequuntur officia consequatur aliquam soluta exercitationem dignissimos.
                   Tempora eos blanditiis eius omnis rem alias eaque vitae porro atque possimus? Possimus sunt vero soluta voluptate ullam minima, repellendus laborum odio iste, eveniet debitis esse inventore praesentium, nisi unde.
                   Eos libero odit earum ipsa corrupti magnam assumenda? Reprehenderit velit excepturi odio consequuntur neque! Quod molestias suscipit officiis harum distinctio ullam tenetur accusantium odit fugit, reprehenderit fuga nostrum nulla labore.
                   Fugit repudiandae magni minus dolor eligendi voluptatum numquam maiores labore officiis corporis modi necessitatibus ullam libero alias harum aspernatur, incidunt nobis maxime quod consequatur, porro omnis commodi facilis vitae! Ullam.
                   Ad labore necessitatibus delectus suscipit dolor! Voluptas, ipsa provident voluptate eveniet, vel distinctio quam atque alias impedit reprehenderit harum! Molestias iure laboriosam cupiditate soluta debitis. Consequuntur laboriosam ad impedit. Nesciunt?
                   Optio quas dolorum magni vero deserunt eligendi, recusandae eum non iusto, autem quo veniam, quam sequi nobis reiciendis. Soluta quae incidunt aspernatur laudantium sunt reprehenderit reiciendis eveniet consequuntur modi cumque.
                   Ipsa quaerat ratione ad perspiciatis est fugiat vitae qui tenetur voluptatum, iusto temporibus porro corporis sequi assumenda et nulla rerum quasi optio eligendi non quis architecto! Nesciunt neque impedit deserunt.
                   Temporibus nihil deserunt voluptates vel consequuntur facere ullam labore dicta? Delectus provident corrupti ratione beatae? Quas laboriosam nulla illum repellendus. Cum fugiat, repudiandae nesciunt a itaque veniam in quibusdam nam.
                   Debitis, laboriosam molestias. Numquam aspernatur officiis at repudiandae nesciunt porro harum voluptatum obcaecati consequuntur explicabo. Enim laudantium, vero hic quae excepturi atque omnis quasi, eveniet neque, dolorem eligendi ex facere?
                   Dolores minus officiis quam repellendus consequuntur soluta illo molestias modi odio quasi voluptas dicta veritatis quos suscipit est dolorem labore reprehenderit cum aliquam, necessitatibus odit magnam! Pariatur odit natus accusantium.
                   Voluptates eaque libero enim, adipisci minima quam ipsam. Assumenda in reprehenderit facilis est, error eos nihil harum, id aut provident itaque totam? Voluptates est sint reprehenderit debitis dolorum, error nobis.
                   Modi quisquam ut tenetur laborum, illo ratione esse ad aspernatur saepe officiis nostrum tempora, assumenda corporis excepturi in repellat eius dicta labore? Reiciendis fuga expedita natus quidem sequi facilis hic.
                   Doloremque eius, laudantium corrupti itaque sint sed vero error, rerum dolores quasi doloribus! Maiores, quas ducimus. Minus, voluptates? Recusandae, ad architecto. Magnam accusantium consectetur optio sit vel? Odit, tempore maiores!
                   Culpa distinctio, officia ratione doloribus provident minus! Voluptatibus a ullam ipsa nobis earum suscipit debitis. Amet exercitationem, laboriosam illo iste sunt repellat et distinctio accusantium sint ratione unde nam consequatur?
                   Impedit perferendis laboriosam praesentium cumque qui? Libero voluptatem commodi nobis laborum dolore dolorem, maxime odit eveniet unde similique nesciunt quae fugiat distinctio earum, qui natus laudantium aliquam, provident maiores enim!
                   Obcaecati sapiente nostrum, dolorem quis possimus consequuntur voluptates et molestiae facere! At soluta dolores animi mollitia voluptas sapiente autem expedita deserunt nobis voluptate assumenda aut cum, hic cupiditate perferendis. Amet.
                   Est eveniet velit nostrum harum eligendi ratione natus consequatur sapiente architecto, libero dolor! Consectetur autem blanditiis nemo nam eos dolore, soluta aspernatur unde nobis magni sequi! Earum odio rem pariatur?
                   Ullam perspiciatis suscipit alias blanditiis consequuntur ratione deserunt? Dolorum aspernatur reiciendis quia! Excepturi, nobis blanditiis ad distinctio exercitationem sit sapiente qui! Doloremque esse dolorum quidem ducimus aliquam aliquid natus. Hic!
                   Porro ullam unde iure dicta explicabo qui pariatur quasi nobis accusamus dignissimos ipsam, commodi in veniam nemo eos ipsum laborum. Et blanditiis eligendi modi delectus tempore ea reiciendis odio ex!
                   Reiciendis deserunt reprehenderit eius sequi, facilis nulla dignissimos inventore adipisci, et cumque laboriosam eveniet beatae totam saepe corporis ut quam velit architecto magnam labore. Consequatur architecto optio tempore mollitia eveniet!
                   Impedit quos doloribus ullam vel in est neque, alias id voluptatibus sed ab consequatur commodi temporibus et earum itaque iste dolor! Maiores ducimus mollitia autem ad? Laboriosam magni dolorum eligendi.
                   Et quia enim expedita. Quo corrupti, officia ullam tempora deserunt iste repudiandae voluptas vitae harum eligendi deleniti, tenetur saepe laboriosam ipsum quibusdam mollitia quaerat laborum eum odio delectus consequatur nam.
                   Laboriosam modi quia voluptatibus aspernatur corporis. Omnis dolor, eveniet, voluptatibus ducimus soluta illum hic laboriosam laudantium labore quia vel eligendi autem culpa quos voluptate quisquam ut repudiandae porro! Labore, praesentium?
                   Aliquam animi soluta cupiditate saepe unde non quidem ea nisi ipsam, et commodi expedita architecto eius voluptates! Quaerat eveniet id debitis repellendus a ipsum perspiciatis soluta totam, placeat vel similique.
                   Modi doloribus omnis voluptates incidunt quo dignissimos tempore praesentium, quam sint ex aut repellat alias, illo non, minus aliquam placeat. Animi exercitationem maxime obcaecati, itaque perspiciatis cum? Hic, ex quam.
                   Obcaecati, corporis nulla laudantium accusantium quo cupiditate placeat eos, pariatur eveniet officia maiores consequuntur et ab, quas laborum culpa molestiae natus. Magni a expedita officia libero assumenda. Harum, dolor eius.
                   Architecto consequatur obcaecati reprehenderit saepe vitae assumenda officia doloribus animi eos commodi magni laboriosam natus repellat expedita excepturi, ducimus explicabo porro eum nam iure quasi! Perferendis quis iusto iure officia.
                   Quis labore iusto maiores iste nesciunt saepe doloribus assumenda tenetur esse nostrum ipsam quia excepturi dicta omnis nobis ipsa itaque odit minus, dolorum reprehenderit deleniti sunt fugit autem? Maiores, enim.
                   Numquam quas nulla delectus ex, eligendi omnis quae architecto ipsa nihil totam laboriosam perferendis dolores? Omnis molestias officiis totam corporis dolorum, iure voluptatibus? Tenetur ea, assumenda eum consectetur autem voluptas?
                   Incidunt minus porro nam expedita autem necessitatibus aliquid. Maxime corporis iusto id facere. Esse doloremque quidem beatae, quis neque molestiae eaque ex minima sunt optio consequatur mollitia nesciunt ducimus voluptate.
                   Eligendi sequi perspiciatis necessitatibus qui mollitia dolores totam quo deserunt, quas obcaecati eveniet officia saepe maxime quis ipsa alias hic voluptatibus aspernatur velit quod? Ratione rem vel fuga aliquam modi.
                   Illo eaque ea esse quidem? Pariatur illum dolores expedita nostrum vel? Minus nam in, incidunt autem laudantium aut molestiae labore totam. Quo nisi sapiente temporibus praesentium? Aspernatur aut corrupti voluptas?
                   Reprehenderit reiciendis sequi praesentium optio impedit id ex est velit minima recusandae, natus, eligendi autem aut, nulla laborum consectetur ipsum. Inventore expedita similique asperiores beatae, pariatur tempora. Non, ad sed?
                   Voluptatibus sint est nam et ducimus suscipit similique maxime corporis quos voluptate quae aliquam, ab nobis a quasi laborum assumenda pariatur velit dicta repellat culpa. Quae optio commodi amet nemo?
                   Aliquam veniam corporis repellat illo cupiditate. Nostrum odio suscipit veritatis quia ipsa, sit libero quibusdam earum voluptatum, eum mollitia inventore incidunt ducimus qui nihil error. Laborum ipsam ut debitis voluptas!
                   Molestiae exercitationem dignissimos in ratione beatae mollitia corporis iure itaque qui maiores rem aut modi quas, iusto cumque tempora ipsa repudiandae vel illum consequatur molestias? Nam cumque atque cupiditate ut!
                   Doloribus libero ullam, perferendis natus molestiae deserunt vitae velit earum hic, magni nam sequi possimus nisi quisquam saepe eaque perspiciatis voluptate corrupti eveniet quod, repellat labore minus. Dicta, hic iusto.
                   Illum illo praesentium, eaque temporibus ex unde? Veniam vitae excepturi perspiciatis amet delectus ea praesentium nostrum exercitationem minima ab minus dolores consequatur magni porro quae officia, molestias ipsum vero maiores!
                   Est harum dicta dolores soluta, officiis suscipit tenetur aperiam culpa velit hic dolorem unde ipsum dolorum ab optio quis, beatae commodi exercitationem! Debitis nihil consequuntur eius placeat incidunt officia est?
                   Architecto velit ut error quaerat sed iure, facere quasi quod quas omnis nulla dicta nesciunt molestiae suscipit cum impedit dolore voluptas? Natus asperiores, at quibusdam a cum sint earum architecto?
                   Quidem sapiente, ipsum laborum eos exercitationem cupiditate esse tempore repellat voluptas ullam dolores pariatur recusandae rem fugit necessitatibus provident voluptatem labore, praesentium officia architecto dolorem! Dolorum quam repellat consectetur officiis!
                   Unde debitis velit tempora rem, numquam obcaecati. Delectus, nesciunt rem necessitatibus vel recusandae laborum maiores aspernatur excepturi eum asperiores quaerat vero cupiditate ipsa totam atque aliquam est eos at! Quasi?
                   Perferendis, maxime aliquam officia quasi possimus enim. Iste minima facilis repudiandae veniam explicabo eligendi, rem maiores? Vel itaque qui incidunt cum? Beatae dolore labore eaque non perspiciatis voluptatibus minus assumenda.
                   Officiis nisi sunt aspernatur iure illum provident vero libero quasi deleniti! Necessitatibus, aspernatur? Recusandae ex temporibus, ipsum earum, corrupti aliquam ratione amet tenetur, impedit suscipit cum? Excepturi nulla explicabo est.
                   Vero esse quia beatae ab autem odio provident nam facere obcaecati nesciunt recusandae id repellendus corrupti perferendis earum, in exercitationem dolores rem illo! Dicta vel in id, deleniti quo doloremque?
                   Quaerat maxime modi aperiam facilis sunt consequuntur at culpa aut, unde inventore explicabo dolore porro cupiditate est accusantium sapiente incidunt distinctio quia. Ea explicabo impedit atque deleniti repellendus cumque ratione.
                   Itaque dolorum laboriosam in accusamus? Animi quos enim soluta officiis voluptatem quo vitae velit tempora facilis commodi ad officia amet asperiores dolorem autem ab odio hic tenetur, doloremque quod exercitationem!
                   Soluta mollitia maxime voluptatibus qui animi dolorum rerum perferendis, architecto deserunt. Fugit accusamus commodi amet ratione sequi? Ipsa, illum cum! Quibusdam hic sapiente quisquam, ipsam facilis autem omnis accusamus soluta.
                   Praesentium aut quam quo officia et quia impedit deserunt laudantium saepe quisquam, nam nulla dolorum doloremque! Velit, a. Delectus mollitia fugit debitis repellendus laudantium illum at magnam placeat quae laborum.
                   Officia, quisquam? Vel neque possimus placeat ex quod laborum, explicabo quae eum sint provident officia tenetur dolor sequi quibusdam in minima nihil totam ratione voluptatem suscipit doloremque impedit? Similique, architecto.
                   Magnam voluptatibus minima quibusdam et adipisci quaerat repudiandae nisi iusto maxime dolor ipsum ipsa asperiores, vel labore odio consequatur dolores sapiente! Voluptate nostrum alias magnam molestias nulla quisquam odio non?
                   Officia veniam asperiores explicabo voluptatem voluptate, reiciendis nesciunt sed ipsam pariatur distinctio rem itaque iure quis nulla quia. Quis in quasi quidem, culpa ratione alias corrupti illum cupiditate incidunt voluptatum!
                   Laborum, accusantium! Ea sequi at veniam aperiam minus placeat nisi facilis, officiis, doloremque quis eligendi exercitationem ullam! Quia iste voluptas numquam eum nemo! Doloribus inventore expedita quibusdam error pariatur numquam.
                   Culpa, quos natus deleniti maxime laudantium error cumque reiciendis dolorum hic harum vitae ullam possimus nemo blanditiis omnis iure voluptas iusto vero. Nesciunt explicabo ad molestias placeat quod. Recusandae, rerum?
                   Neque facilis tempore nesciunt, dolores tenetur placeat maiores quos reprehenderit dolorum sequi unde impedit eum amet iusto aperiam! Vitae recusandae dolores eaque ratione. Asperiores eveniet soluta dolorum sapiente numquam. Fuga.
                </Text>
            </ScrollView>
        </View>
    );
}
